image: node:16

stages:
  - build
  - deploy

variables:
    NX_FIREBASE_API_KEY: ${NX_FIREBASE_API_KEY}
    NX_FIREBASE_AUTH_DOMAIN: ${NX_FIREBASE_AUTH_DOMAIN}
    NX_FIREBASE_PROJECT_ID: ${NX_FIREBASE_PROJECT_ID}
    NX_FIREBASE_STORAGE_BUCKET: ${NX_FIREBASE_STORAGE_BUCKET}
    NX_FIREBASE_MESSAGING_SENDER_ID: ${NX_FIREBASE_MESSAGING_SENDER_ID}
    NX_FIREBASE_APP_ID: ${NX_FIREBASE_MESSAGING_SENDER_ID}
    NX_FIREBASE_MEASUREMENT_ID: ${NX_FIREBASE_MEASUREMENT_ID}

build:
  only:
    refs:
      - development
  stage: build
  before_script:
    - npm i
  script:
    - npm run build:mui
    - npm run build:antd
    - npm run build:tailwind
    - npm run build:semantic
    - npm run build:prime
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: push  
  environment:
    name: 'Development'
  artifacts:
    expire_in: '300'
    paths:
      - dist/apps

deploy:
  only:
    refs:
      - development

  stage: deploy
  script:
    - npm i -g firebase-tools
    - npx firebase use default
    - npx firebase deploy --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:mui --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:antd --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:prime --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:semantic --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:tailwind --token $FIREBASE_TOKEN

  environment:
    name: 'Development'
