image: node:16.14.2

stages:
  - build
  - deploy

variables:
    NX_FIREBASE_API_KEY: ${NX_FIREBASE_API_KEY}
    NX_FIREBASE_AUTH_DOMAIN: ${NX_FIREBASE_AUTH_DOMAIN}
    NX_FIREBASE_PROJECT_ID: ${NX_FIREBASE_PROJECT_ID}
    NX_FIREBASE_STORAGE_BUCKET: ${NX_FIREBASE_STORAGE_BUCKET}
    NX_FIREBASE_MESSAGING_SENDER_ID: ${NX_FIREBASE_MESSAGING_SENDER_ID}
    NX_FIREBASE_APP_ID: ${NX_FIREBASE_MESSAGING_SENDER_ID}
    NX_FIREBASE_MEASUREMENT_ID: ${NX_FIREBASE_MEASUREMENT_ID}

build-mui:
  only:
    refs:
      - development
  stage: build
  before_script:
    - npm ci --cache .npm --prefer-offline --force
  script:
    - npm run build:mui
  environment:
    name: 'Development'
  artifacts:
    expire_in: '300'
    paths:
      - dist/apps/mui

deploy:
  only:
    refs:
      - development

  stage: deploy
  before_script:
    - npm i -g firebase-tools
  script:
    - firebase deploy --token $FIREBASE_TOKEN

  environment:
    name: 'Development'
